"""Physics-based forward models for EOG measurements.

The two models in this module describe how a three-dimensional eye dipole
produces voltages at EOG electrodes.

``FarFieldDipole`` is the usual point-dipole approximation. It is linear in
``p`` and therefore has one fixed observation matrix ``C``.

``NearFieldDipole`` keeps the two poles of the eye dipole separate. It is more
geometrically faithful when electrodes are not very far from the eye, but the
mapping from dipole vector to EOG is nonlinear because rotating the dipole also
moves the two poles relative to each electrode.
"""

import numpy as np


class FarFieldDipole:
    """Linear point-dipole EOG forward model.

    The model is

        y = C @ p

    where ``p`` is the 3-D eye dipole vector and ``y`` contains the recorded
    EOG channels after the montage has been applied.

    Parameters
    ----------
    geometry : EyeGeometry
        Electrode locations relative to the center of the eye, in meters.
    montage : Montage
        Linear map from individual electrode potentials to recorded EOG
        channels, for example right-minus-left and up-minus-down.
    gain : float, default=1.0
        Overall multiplicative scale factor. This can absorb constants such as
        effective conductivity and any unit conversion used by the recording.

    Attributes
    ----------
    C : numpy.ndarray, shape (n_channels, 3)
        Physics-derived linear observation matrix. ``C @ p`` predicts the EOG
        channels generated by dipole vector ``p``.
    """

    nonlinear = False

    def __init__(self, geometry, montage, gain=1.0):
        if montage.n_electrodes != geometry.n_electrodes:
            raise ValueError("montage columns must match geometry electrodes")

        self.geometry = geometry
        self.montage = montage
        self.gain = float(gain)

        # Every electrode position is measured from the eye center. For the
        # point-dipole approximation, sensitivity falls as 1 / distance^2 and
        # points along the eye-center-to-electrode direction.
        r = geometry.positions
        distance = np.linalg.norm(r, axis=1)
        if np.any(distance == 0):
            raise ValueError("an electrode cannot lie at the eye center")

        self.electrode_lead_field = r / distance[:, None] ** 3

        # Electrode potentials are converted into the EOG channels that were
        # actually recorded, such as R-L or U-D.
        self.C = self.gain * montage.matrix @ self.electrode_lead_field

    def electrode_potentials(self, p):
        """Predict the potential at each physical electrode.

        Parameters
        ----------
        p : numpy.ndarray, shape (3,)
            Three-dimensional eye dipole vector.

        Returns
        -------
        potentials : numpy.ndarray, shape (n_electrodes,)
            Predicted potential at each electrode before re-referencing or
            bipolar channel construction.
        """
        p = np.asarray(p, dtype=float)
        return self.gain * self.electrode_lead_field @ p

    def observe(self, p):
        """Predict recorded EOG channels for one dipole vector."""
        return self.C @ np.asarray(p, dtype=float)

    def jacobian(self, p=None):
        """Return the observation Jacobian, which is simply ``C`` here."""
        return self.C

    @property
    def rank(self):
        """Rank of the linear observation matrix ``C``."""
        return int(np.linalg.matrix_rank(self.C))

    @property
    def condition_number(self):
        """Condition number of ``C``; large values indicate poor geometry."""
        singular_values = np.linalg.svd(self.C, compute_uv=False)
        if len(singular_values) < 3 or singular_values[-1] == 0:
            return np.inf
        return float(singular_values[0] / singular_values[-1])


class NearFieldDipole:
    """Finite two-pole EOG forward model.

    This model keeps the positive and negative poles of the eye dipole at
    separate positions. If ``p`` is the dipole moment and ``s`` is the chosen
    pole separation,

        direction = p / ||p||
        r_plus    = +(s / 2) * direction
        r_minus   = -(s / 2) * direction
        q         = ||p|| / s

    The potential at electrode ``i`` is then proportional to

        q * (1 / ||r_i - r_plus|| - 1 / ||r_i - r_minus||).

    Choosing ``q = ||p|| / s`` preserves the dipole moment because
    ``q * (r_plus - r_minus) = p``. As electrodes become far away relative to
    ``s``, this model approaches the linear point-dipole model.

    Parameters
    ----------
    geometry : EyeGeometry
        Electrode locations relative to the center of the eye, in meters.
    montage : Montage
        Linear map from individual electrode potentials to recorded channels.
    source_separation : float, default=0.020
        Distance between the positive and negative poles, in meters. A value of
        ``0.020`` corresponds to 20 mm. This is intentionally exposed because
        changing it alters how strongly near-field geometry matters.
    gain : float, default=1.0
        Overall multiplicative scale factor applied to predicted voltages.
    jacobian_eps : float, default=1e-6
        Relative finite-difference step used to calculate the local Jacobian
        needed by the extended Kalman filter.
    """

    nonlinear = True

    def __init__(
        self,
        geometry,
        montage,
        source_separation=0.020,
        gain=1.0,
        jacobian_eps=1e-6,
    ):
        if montage.n_electrodes != geometry.n_electrodes:
            raise ValueError("montage columns must match geometry electrodes")
        if source_separation <= 0:
            raise ValueError("source_separation must be positive")

        self.geometry = geometry
        self.montage = montage
        self.source_separation = float(source_separation)
        self.gain = float(gain)
        self.jacobian_eps = float(jacobian_eps)

    def electrode_potentials(self, p):
        """Predict physical electrode potentials from one dipole vector.

        Parameters
        ----------
        p : numpy.ndarray, shape (3,)
            Three-dimensional dipole moment vector. Its direction sets the
            orientation of the two poles; its magnitude sets pole strength.

        Returns
        -------
        potentials : numpy.ndarray, shape (n_electrodes,)
            Potential at each physical electrode before applying the montage.
        """
        p = np.asarray(p, dtype=float)
        if p.shape != (3,):
            raise ValueError("p must have shape (3,)")

        magnitude = np.linalg.norm(p)
        if magnitude < 1e-15:
            return np.zeros(self.geometry.n_electrodes)

        direction = p / magnitude
        half_separation = 0.5 * self.source_separation

        # The eye center is the origin of EyeGeometry, so the two poles sit on
        # opposite sides of that origin along the current dipole direction.
        positive_pole = half_separation * direction
        negative_pole = -half_separation * direction

        electrode_positions = self.geometry.positions
        distance_to_positive = np.linalg.norm(
            electrode_positions - positive_pole,
            axis=1,
        )
        distance_to_negative = np.linalg.norm(
            electrode_positions - negative_pole,
            axis=1,
        )

        if np.any(distance_to_positive == 0) or np.any(distance_to_negative == 0):
            raise ValueError("a dipole pole coincides with an electrode position")

        # Scaling pole strength by 1 / separation keeps the dipole moment equal
        # to p when source_separation is changed.
        pole_strength = magnitude / self.source_separation

        return self.gain * pole_strength * (
            1.0 / distance_to_positive - 1.0 / distance_to_negative
        )

    def observe(self, p):
        """Predict recorded EOG channels for one dipole vector."""
        electrode_voltage = self.electrode_potentials(p)
        return self.montage.matrix @ electrode_voltage

    def jacobian(self, p):
        """Return the local observation matrix d h(p) / d p.

        The finite two-pole model is nonlinear in dipole direction, so it does
        not have one global matrix ``C``. The extended Kalman filter instead
        needs the local slope of the forward model around its current estimate.
        A centered finite difference is used here because it is transparent and
        easy to verify.
        """
        p = np.asarray(p, dtype=float)
        if p.shape != (3,):
            raise ValueError("p must have shape (3,)")

        H = np.zeros((self.montage.n_channels, 3), dtype=float)
        for dimension in range(3):
            step = self.jacobian_eps * max(1.0, abs(p[dimension]))
            delta = np.zeros(3)
            delta[dimension] = step

            y_plus = self.observe(p + delta)
            y_minus = self.observe(p - delta)
            H[:, dimension] = (y_plus - y_minus) / (2.0 * step)

        return H
